Fixes "ContentScopeScripts" building issue (#625)
Task/Issue URL:
https://app.asana.com/1/137249556945/project/1201037661562251/task/1210115274395884?focus=true

### Description

Resolves a common build issue we've been seeing recently.

> error: remove failed
remove(/Users/ddg/Library/Developer/Xcode/DerivedData/DuckDuckGo-cwxizrjfhszusnhlertkynlioqyr/Build/Products/Debug/DuckDuckGo
Personal Information
Removal.app/Contents/Resources/ContentScopeScripts_ContentScopeScripts.bundle/Contents/Resources/pages/new-tab/company-icons):
Directory not empty (66) (in target 'DuckDuckGoDBPBackgroundAgent' from
project 'DuckDuckGo-macOS')

This is caused by a script in the build steps that's called "Copy Swift
Package resources".

It was implemented to resolve [this
issue](https://forums.swift.org/t/swift-packages-resource-bundle-not-present-in-xcarchive-when-framework-using-said-package-is-archived/50084/2),
but only needs to be run for archive / install builds.

### Testing Steps

Just build a couple of times and make sure you get no errors about
`ContentScopeScripts`. Make sure the CI goes green.

### Impact and Risks

Low: I can think this would affect anything as it was implemented for
archive builds (ie: install builds).

#### What could go wrong?

NA

### Quality Considerations

NA

### Notes to Reviewer

NA

---
###### Internal references:
[Definition of
Done](https://app.asana.com/0/1202500774821704/1207634633537039/f) |
[Engineering
Expectations](https://app.asana.com/0/59792373528535/199064865822552) |
[Tech Design
Template](https://app.asana.com/0/59792373528535/184709971311943)